# SPECIATION
COMPATABILITY_THRESHOLD = 3.0
EXCESS_IMPORTANCE = 1.0
DISJOINT_IMPORTANCE = 1.0
WEIGHT_DIFFERENCE_IMPORTANCE = 0.4
DELTA_NORMALIZATION_THRESHOLD = 20
SPECIES_STAGNATE_MIN_IMPROVEMENT = 0.1
SPECIES_STAGNATE_GEN_COUNT = 2

# EVOLUTION
POPULATION_SIZE = 100
GENERATIONS = 1000

# MUTATION
CONNECTION_MUTATE_PROBABILITY = 0.8
WEIGHT_PERTURB_PROBABILITY = 0.9
WEIGHT_RANDOMIZE_PROBABILITY = 0.1
ADD_NODE_MUTATE_PROBABILITY = 0.03
ADD_CONNECTION_MUTATE_PROBABILITY = 0.05
WEIGHT_PURTURB_RANGE = 2


# CROSSOVER
INTERSPECIES_MATING_RATE = 0.001
PARENT_GENE_DISABLE = 0.75
