# SPECIATION
COMPATABILITY_THRESHOLD = 3.0
EXCESS_IMPORTANCE = 1.0
DISJOINT_IMPORTANCE = 1.0
WEIGHT_DIFFERENCE_IMPORTANCE = 0.4
DELTA_NORMALIZATION_THRESHOLD = 20

#EVOLUTION
POPULATION_SIZE = 100
GENERATIONS = 1000
